fix(#168): set login url next parameter
Radi85/Comment pull request #185
Opened 2021-03-27 10:37 UTC by ZendaInnocent

Set login url next parameter to absolute url of the model object.

fixes #168

2021-03-27 14:46 UTC, abhiabhi94 requested changes
Hey @ZendaInnocent, this will not fix the actual problem, it just fixes this part of the template. There are other parts that need the `request` object.

If you really want to have a stab at this, you will have to add the `request` object to the `context` dictionary here:

https://github.com/Radi85/Comment/blob/0d7bc4b99fa5573fe4bbda9ab8f32099ed8f4ffe/comment/templatetags/comment_tags.py#L74-L82
`request` is already available in this function.

Also, you will probably need to change the current tests, I think

2021-03-27 19:09 UTC, ZendaInnocent commented
Adding `request` object in `DABContext.__call__` method won't be sufficient?

I tried to add it there and seems to work fine.

2021-03-28 01:09 UTC, abhiabhi94 commented
> Adding `request` object in `DABContext.__call__` method won't be sufficient?
> 
> I tried to add it there and seems to work fine.

The `DABContext` call is [used in most of the views](https://github.com/Radi85/Comment/blob/develop/comment/mixins.py#L41) when rendering a template.
When rendering a template using the method `rendering_to_string`, [a lot of metadata is passed to the template by Django](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.loader.render_to_string). `request` is one of them.

So, my point is request is already available for other templates that are rendered through views. It is not available in this case, because we are using `inclusion_tag` to render the template, and it was not passed explicitly by it.

In short, adding `request` to `DABContext` seems more of an overkill to me, just adding it to the `context` dictionary used by `render_comments` template tag should be sufficient in this case.

2021-03-28 05:05 UTC, ZendaInnocent commented
Thanks for the explanations.

2021-03-28 05:17 UTC, abhiabhi94 commented on comment/tests/test_template_tags.py
> +        self.assertIsInstance(data['request'], WSGIRequest)
perhaps this should be:
```suggestion
        self.assertEqual(data['request'], request)
```

2021-03-28 05:31 UTC, abhiabhi94 approved these changes
Thanks!

2021-03-28 10:26 UTC, Radi85 commented
@ZeroCoolHacker @abhiabhi94 
I see that @ZendaInnocent first solution is more eligible. The request object is only needed here to get the path value which is already available for us with `model_object.get_absolute_url`.

2021-03-28 10:29 UTC, Radi85 commented
PS: First solution was replacing `request.path` with `model_object.get_absolute_url` in the template and it is sufficient.

2021-03-28 11:46 UTC, abhiabhi94 commented
> PS: First solution was replacing request.path with model_object.get_absolute_url in the template and it is sufficient.

Actually the `request` object is also used to redirect after login for other things like :+1: , unlike, flag, subscribe etc, so adding `request` would require lesser work.

Also, `model_obj.absolute_url` would not wouldn't always be correct especially when the comment is not on the first page. 
e.g `/post?page=2`

2021-03-28 12:02 UTC, Radi85 approved these changes

2021-03-28 12:02 UTC, merged

2021-03-28 12:03 UTC, Radi85 commented
Thanks @ZendaInnocent for your contribution!

2021-03-28 12:19 UTC, abhiabhi94 commented
I think the commit message should have been something similar to the one that is the title of the issue closed at the moment. This will be potentially more helpful in generating the `changelog` and also puts the change in the perspective of the end user.
Although, I am the one to blame, I edited it as a lesser appropriate one earlier.

2021-03-29 04:36 UTC, ZendaInnocent commented
> I think the commit message should have been something similar to the one that is the title of the issue closed at the moment. This will be potentially more helpful in generating the `changelog` and also puts the change in the perspective of the end user.
> Although, I am the one to blame, I edited it as a lesser appropriate one earlier.

Amending the commit and push to the branch will work?

2021-03-29 04:38 UTC, abhiabhi94 commented
> Amending the commit and push to the branch will work?

No issues, it was just a reminder for the future.

2021-03-29 04:39 UTC, ZendaInnocent commented
> > Amending the commit and push to the branch will work?
> 
> No issues, it was just a reminder for the future.

Okay, thanks.